# Generated by Django 5.1.7 on 2025-04-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50, verbose_name='Nome:')),
                ('RA', models.CharField(blank=True, max_length=50, null=True, verbose_name='RA:')),
                ('Sala', models.CharField(max_length=50, verbose_name='Sala:')),
                ('Serie', models.CharField(max_length=5, verbose_name='Série:')),
                ('Livro_em_posse', models.CharField(max_length=256, blank=True, verbose_name='Livro em posse:')),
                ('Data_coleta', models.DateField(null=True, blank=True, verbose_name='Data de coleta:')),
                ('Data_devolução', models.DateField(blank=True, null=True, verbose_name='Data de Devolução:')),
                ('Observacao', models.TextField(blank=True, null=True, verbose_name='Observação:')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=100, verbose_name='Autor:')),
                ('Titulo', models.CharField(max_length=100, verbose_name='Título:')),
                ('Em_uso', models.BooleanField(default=False, verbose_name='Em uso:')),
                ('Subtitulo', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Subtítulo:')),
                ('Colecao', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Coleção:')),
                ('Serie', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Série:')),
                ('Edicao', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Edição:')),
                ('Volume', models.IntegerField(blank=True, default=None, null=True, verbose_name='Volume:')),
                ('Local', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Local:')),
                ('Editora', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Editora:')),
                ('Ano_Publicacao', models.DateField(blank=True, default=None, null=True, verbose_name='Ano de Publicação:')),
                ('Aquisicao', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Aquisição:')),
                ('Exemplar', models.IntegerField(blank=True, default=None, null=True, verbose_name='Exemplar:')),
                ('Idioma', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Idioma:')),
                ('Paginas', models.IntegerField(blank=True, default=None, null=True, verbose_name='Páginas:')),
                ('Tombo', models.IntegerField(blank=True, default=None, null=True, verbose_name='Tombo:')),
                ('Data_Tombo', models.DateField(blank=True, default=None, null=True, verbose_name='Data Tombo:')),
                ('Data_Registro', models.DateField(blank=True, default=None, null=True, verbose_name='Data de Registro:')),
                ('ISBN', models.IntegerField(blank=True, default=None, null=True, verbose_name='ISBN:')),
                ('Cod_Barras', models.IntegerField(blank=True, default=None, null=True, verbose_name='Código de barras:')),
                ('Data_Baixa', models.DateField(blank=True, default=None, null=True, verbose_name='Data de baixa:')),
                ('Observacao', models.TextField(blank=True, default=None, null=True, verbose_name='Observação:')),
                ('Classif_CDD', models.IntegerField(blank=True, default=None, null=True, verbose_name='Classificação CDD:')),
                ('Assunto', models.TextField(blank=True, default=None, null=True, verbose_name='Assunto:')),
                ('Prateleira', models.CharField(max_length=100, verbose_name='Prateleira:')),
            ],
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=100, verbose_name='Autor:')),
                ('Titulo', models.CharField(max_length=100, verbose_name='Título:')),
                ('Em_uso', models.BooleanField(default=False, verbose_name='Em uso:')),
                ('Subtitulo', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Subtítulo:')),
                ('Colecao', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Coleção:')),
                ('Local', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Local:')),
                ('Idioma', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Idioma:')),
                ('Ano_Publicacao', models.DateField(blank=True, default=None, null=True, verbose_name='Ano de Publicação:')),
                ('Aquisicao', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Aquisição:')),
                ('Exemplar', models.IntegerField(blank=True, default=None, null=True, verbose_name='Exemplar:')),
                ('Tombo', models.IntegerField(blank=True, default=None, null=True, verbose_name='Tombo:')),
                ('Data_Tombo', models.DateField(blank=True, default=None, null=True, verbose_name='Data Tombo:')),
                ('Data_Registro', models.DateField(blank=True, default=None, null=True, verbose_name='Data de Registro:')),
                ('ISBN', models.IntegerField(blank=True, default=None, null=True, verbose_name='ISBN:')),
                ('Numero', models.IntegerField(blank=True, default=None, null=True, verbose_name='Número:')),
                ('Cod_Barras', models.IntegerField(blank=True, default=None, null=True, verbose_name='Código de barras:')),
                ('Data_Baixa', models.DateField(blank=True, default=None, null=True, verbose_name='Data de baixa:')),
                ('Observacao', models.TextField(blank=True, default=None, null=True, verbose_name='Observação:')),
                ('Prateleira', models.CharField(max_length=100, verbose_name='Prateleira:')),
            ],
        ),
    ]
